services:
  api:
    build: ./api
    container_name: brad-api
    ports:
      - "${PORT}:${PORT}" 
    volumes:
      - ./api:/app
      - ./uploads:/uploads
    depends_on:
      - mongo
      - fastapi-queue
    env_file:
      - .env

  bot:
    build: ./bot
    container_name: brad-bot
    volumes:
      - ./bot:/app
    depends_on:
      - redis
      - api
      - mongo
    env_file:
      - .env

  fastapi-queue:
    build: ./fastapi-queue
    container_name: brad-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./fastapi-queue:/app

  frontend:
    build: ./frontend
    container_name: brad-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo
    container_name: brad-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./database/mongo.conf:/etc/mongo.conf:ro
    command: mongod --quiet --logpath /var/log/mongodb/mongod.log

  redis:
    image: redis:7-alpine
    container_name: brad-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
