services:
  api:
    build: ./api
    container_name: brad-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/brad_db
      - JWT_SECRET=brad_super_secret_2025
      - BOT_ACCESS_KEY=secret-bot-key-123
      - PORT=3000
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_redis_password
      - EMAIL_USER=cos301.cap2@gmail.com
      - EMAIL_PASS=cmzu mhnu dvds sadx

  bot:
    build: ./bot
    container_name: brad-bot
    volumes:
      - ./bot:/app
    depends_on:
      - redis
      - api
      - mongo
    environment:
      - API_URL=http://api:3000
      - BOT_ACCESS_KEY=secret-bot-key-123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_redis_password
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: brad-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo
    container_name: brad-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./database/mongo.conf:/etc/mongo.conf:ro
    command: mongod --quiet --logpath /var/log/mongodb/mongod.log

  redis:
    image: redis:7-alpine
    container_name: brad-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass "your_redis_password"
    environment:
      - REDIS_PASSWORD=your_redis_password
    volumes:
    - redis-data:/data

volumes:
  mongo-data:
  redis-data:
