services:
  api:
    build: ./api
    container_name: brad-api
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./api:/app
      - ./uploads:/uploads
    depends_on:
      - mongo
    env_file:
      - .env

  bot:
    build: ./bot
    container_name: brad-bot
    volumes:
      - ./bot:/app
    depends_on:
      - mongo
      - api
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: brad-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo
    container_name: brad-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./database/mongo.conf:/etc/mongo.conf:ro
    command: mongod --quiet --logpath /var/log/mongodb/mongod.log

volumes:
  mongo-data:
