name: BRAD CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
      - pipeline-testing
      - pipeline
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and start services
        run: docker compose up -d --build

      # ---------- Frontend ----------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run frontend tests
        working-directory: frontend
        run: npm test

      # ---------- Backend (API) ----------
      - name: Install backend dependencies
        working-directory: api
        run: npm install

      - name: Run backend integration tests
        working-directory: api
        run: npm run test:integration

      # ---------- Bot Runner ----------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run bot-runner tests
        run: pytest bot-runner/tests

      - name: Stop services
        if: always()
        run: docker compose down
