name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API container
        run: docker build -t brad-api ./api

      - name: Build Bot container
        run: docker build -t brad-bot ./bot

      - name: Build Frontend container
        run: docker build -t brad-frontend ./frontend

      # === Only run tests on main ===
      - name: Run API tests
        if: github.ref == 'refs/heads/main'
        run: docker run --rm brad-api npm run test -- --config jest.config.ts

      - name: Run Frontend tests
        if: github.ref == 'refs/heads/main'
        run: docker run --rm brad-frontend npm run test

      - name: Run Bot tests
        if: github.ref == 'refs/heads/main'
        run: docker run --rm brad-bot pytest tests/test_bot.py
